from . import DataType

def string() -> DataType: ...
def is_null(t: DataType) -> bool: ...
def is_string(t: DataType) -> bool: ...
def is_large_string(t: DataType) -> bool: ...
def is_struct(t: DataType) -> bool: ...
